@startuml Manage Bookings (GET All)

header TongA Sequence Diagram
footer Page %page% of %lastpage%
title "Manage Bookings (GET All)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:bookings" as routerBookings
participant "<<controllers>>\n:bookings" as controllersBookings
participant "<<model>>\n:Booking" as modelBooking
database "<<MongoDB>>\n:bookings" as BookingsDatabase

client->server ++: req.get('/bookings')
server->routerBookings ++: app.use('/bookings', bookings)
routerBookings -> controllersBookings ++: getBookings(req, res)
controllersBookings->modelBooking ++: find()
modelBooking -> BookingsDatabase ++: Retrieve all bookings
BookingsDatabase --> modelBooking --: bookings[]
controllersBookings <-- modelBooking --: bookings[]
controllersBookings->client --: response (all bookings)

@enduml
